#########################################################################
# Title:         Saltbox: Sanity Check | Ansible Tags                   #
# Author(s):     desimaniac, EnorMOZ                                    #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Ansible Tags | Check if cache file exists
  ansible.builtin.stat:
    path: /srv/git/sb/cache.json
  register: cache_file_stat

- name: Ansible Tags | Load tags from cache if available
  when: cache_file_stat.stat.exists and (sanity_check_use_cache | bool)
  block:
    - name: Ansible Tags | Load tags from cache if available
      ansible.builtin.set_fact:
        loaded_tags: "{{ (lookup('file', '/srv/git/sb/cache.json') | from_json)['/srv/git/saltbox']['tags'] | default([]) + sanity_check_ansible_tags_extra }}"

  rescue:
    - name: Ansible Tags | Delete '/srv/git/sb/cache.json'
      ansible.builtin.file:
        path: "/srv/git/sb/cache.json"
        state: absent

- name: Ansible Tags | Load tags without cache
  when: (loaded_tags is defined and ((loaded_tags | length) == (sanity_check_ansible_tags_extra | length))) or loaded_tags is undefined
  block:
    - name: Ansible Tags | Get all available Ansible tags if cache is not available
      ansible.builtin.shell: "{{ sanity_check_ansible_tags_lookup_command }}"
      register: available_ansible_tags
      changed_when: false

    - name: Ansible Tags | Set loaded tags from command if cache is not available
      ansible.builtin.set_fact:
        loaded_tags: "{{ available_ansible_tags.stdout_lines }}"

- name: Ansible Tags | Ensure valid Ansible tag(s) were provided
  ansible.builtin.assert:
    that:
      - item in loaded_tags
    msg: >-
      You must supply valid tag(s)
      (get a list of valid tags by running 'sb list' or check the meta tags)
    quiet: true
  with_items: "{{ ansible_run_tags }}"
  when: (not continuous_integration) and ('saltbox_mod' not in playbook_dir) and ('sandbox' not in playbook_dir)
