version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
    versioning-strategy: auto
    rebase-strategy: auto
  - package-ecosystem: "pip"
    directory: "/resources/roles/dns/files"
    schedule:
      interval: "daily"
    versioning-strategy: auto
    rebase-strategy: auto
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
