#########################################################################
# Title:         Saltbox: Jellyfin Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Jellyfin roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    jellyfin_name: "{{ instance }}"
  with_items: "{{ jellyfin_instances }}"
  loop_control:
    loop_var: instance
