#########################################################################
# Title:         Saltbox: Radarr Role                                   #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Radarr roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    radarr_name: "{{ instance }}"
  with_items: "{{ radarr_instances }}"
  loop_control:
    loop_var: instance
