##########################################################################################
# Title:         Saltbox: Cloudflare | Configuration Rules | Remove Configuration Rule   #
# Author(s):     salty                                                                   #
# URL:           https://github.com/saltyorg/Saltbox                                     #
# --                                                                                     #
##########################################################################################
#                   GNU General Public License v3.0                                      #
##########################################################################################
---
- name: Configuration Rules | Remove Previous Cloudflare Configuration Rules for Lets Encrypt
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone }}/rulesets/{{ cloudflare_ruleset_id }}/rules/{{ item }}"
    method: DELETE
    headers:
      Content-Type: "application/json"
      X-Auth-Email: "{{ cloudflare.email }}"
      X-Auth-Key: "{{ cloudflare.api }}"
    return_content: true
  loop: "{{ cloudflare_rule_ids }}"
  register: cf_configuration_rule_destruction

- name: Configuration Rules | Print result of Lets Encrypt Cloudflare Configuration Rule Destruction
  ansible.builtin.debug:
    msg: "Successfully deleted Let's Encrypt Cloudflare configuration rule with ID '{{ cloudflare_rule_ids | join(', ') }}'"
