#########################################################################
# Title:         Saltbox: Docker | Daemon Tasks                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Daemon | Create docker directory"
  ansible.builtin.file:
    path: "/etc/docker"
    state: directory
    mode: "0775"
    owner: root
    group: root

- name: "Daemon | Define the 'docker_config' variable"
  ansible.builtin.set_fact:
    docker_config:
      dns: "{{ docker_dns
            if docker_dns | length > 0
            else omit }}"
      fixed-cidr-v6: "{{ '2001:db8::/64'
                      if docker_ipv6
                      else omit }}"
      iptables: true
      ip6tables: "{{ true
                  if docker_ipv6
                  else false }}"
      ipv6: "{{ true
             if docker_ipv6
             else false }}"
      log-driver: "json-file"
      log-opts:
        max-size: "10m"
        max-file: "3"
      storage-driver: "{{ docker_daemon_storage_driver }}"
      userland-proxy: false

- name: "Daemon | Combine 'docker_config' and 'docker_config_custom' and convert to JSON"
  ansible.builtin.set_fact:
    docker_config_json: "{{ (nvidia_docker_config if use_nvidia else {})
                            | combine(docker_config)
                            | combine(docker_config_custom)
                            | to_json(indent=2, sort_keys=True) }}"

- name: "Daemon | Import 'daemon.json'"
  ansible.builtin.copy:
    content: "{{ docker_config_json }}\n"
    dest: "/etc/docker/daemon.json"
    mode: "0664"
    force: "{{ docker_daemon_template_force }}"

- name: "Daemon | Create override directory"
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0755"

- name: "Daemon | Import override file"
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: "0644"
    force: "{{ docker_service_force }}"
