#########################################################################
# Title:         Saltbox: Traktarr | Default Variables                  #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
traktarr_instances: ["traktarr"]
