########################################################################################
# Title:         Saltbox: Settings | Migrator | 'accounts.yml' | Migration 01          #
# Author(s):     desimaniac                                                            #
# URL:           https://github.com/saltyorg/Saltbox                                   #
# --                                                                                   #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################
---
- name: "Migrator | 'accounts.yml' | Migration 01 | Set variables"
  ansible.builtin.set_fact:
    plex_settings: "{{ not ((plex is undefined)
                            or
                            (plex is none)
                            or
                            (plex | trim | length == 0)) }}"

- name: Migrator | 'adv_settings.yml' | Migration 01 | Delete 'plex' dict
  ansible.builtin.shell: |
    yyq -i 'del(.plex)' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: plex_settings

- name: Migrator | 'accounts.yml' | Migration 01 | Remove 'null' values
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/{{ file }}"
    regexp: '(?<=: )\bnull\s*$'
    replace: ''
    owner: "{{ saltbox_yml.stat.uid }}"
    group: "{{ saltbox_yml.stat.gid }}"
    mode: "0664"

- name: Migrator | 'accounts.yml' | Migration 01 | Re-import Variables
  ansible.builtin.include_vars: "{{ playbook_dir }}/{{ file }}"
