#########################################################################
# Title:         Saltbox: User Check                                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Fail if not running as root
  ansible.builtin.fail:
    msg: "This playbook requires root privileges to run."
  when: lookup('env', 'USER') != "root"
