#########################################################################
# Title:         Saltbox: Permissions                                   #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Permissions | Recursively set permissions for '/mnt/local'
  ansible.builtin.shell: "chown -R {{ user.name }}:{{ user.name }} /mnt/local"

- name: Permissions | Recursively set permissions for '/opt'
  ansible.builtin.shell: "chown -R {{ user.name }}:{{ user.name }} /opt"

- name: Permissions | Recursively set permissions for '/home/{{ user.name }}'
  ansible.builtin.shell: "chown -R {{ user.name }}:{{ user.name }} /home/{{ user.name }}"
