#########################################################################
# Title:         Saltbox: Cloudflare Role                               #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Variables Task
  ansible.builtin.import_tasks: "subtasks/variables.yml"

- name: Saltbox Subdomains Task
  ansible.builtin.import_tasks: "subtasks/subdomains.yml"
  when: (saltbox_type | length > 0) and not skip_dns

- name: Purge Cache Task
  ansible.builtin.import_tasks: "subtasks/purge_cache.yml"

- name: Configuration Rules Task
  ansible.builtin.import_tasks: "subtasks/configuration_rules.yml"
