#########################################################################
# Title:         Saltbox: Cloudplow | Disable Task                      #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Delete Service
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/systemd/delete_service.yml"
  vars:
    _service_name: "{{ cloudplow_service_name }}"
